version: '3.8'
services:
  psql-server:
    image: 'postgres'
    environment:
      - POSTGRES_DB=cafeteria
      - POSTGRES_USER=cafeteria
      - POSTGRES_PASSWORD=123456
    networks:
      - backend-local-networks
    ports:
      - '4321:5432'
  adminer:
    image: adminer
    ports:
      - 9000:8080
    networks:
      - backend-local-networks
networks:
  backend-local-networks:
